import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useState } from 'react';

import Card from '@mui/material/Card';
import CardContent from '@mui/material/CardContent';
import logo from '../public/images/logo.svg'

import Container from '@mui/material/Container';
import styles from '../styles/Home.module.css';
import Button from '@mui/material/Button';
import SearchBar from './components/SearchBar'
import Logo from './components/Logo'

const key = 'a44004e391a0422c9d41dc94bdc128af'
const url = 'https://api.nhs.scot/JobsSearch/v1.0.0/Vacancy/GetAllVacs'

const Home: NextPage = () => {
  const [data, setData] = useState([])
  const [featuredData, setFeaturedData] = useState([])
  const [isLoading, setLoading] = useState(false)
  const [pageNumber, setPageNumber] = useState(1)
  const [postNumber] = useState(12) //12 items a page

  const currentPageNumber = (pageNumber * postNumber) - postNumber
  const paginatedPosts = data.splice(currentPageNumber, postNumber)

  const handlePrev = () => {
    if (pageNumber === 1) return
    setPageNumber(pageNumber - 1)
  }
  const handleNext = () => {
    setPageNumber(pageNumber + 1)
  }

  const runThis = () => console.log('ping');
  

  useEffect(() => {
    setLoading(true)
    fetch(url, {
      headers: {
        'Ocp-Apim-Subscription-Key': key
      }
    })
      .then((res) => res.json())
      .then((data) => {
        setData(data)
        setLoading(false)

      })
  }, [])

  if (isLoading) return <p>Loading...</p>
  if (!data) return <p>No profile data</p>



  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.overall_wrapper}>

        <main className={styles.main}>
          <div className={styles.alt_header}>
          <Logo />

          </div>
          <Container className={styles.search_wrapper}>
            
          <h2>Search Results</h2>
              <p>There are <strong>{data.length}</strong> results that match your search</p>

            {/* <SearchBar 
                onInputChange={onInputChange}
                searchParams={searchParams}
                searchParamss={searchParamss}
            /> */}
          </Container>
          <Container>

<div className={styles.pagination}>
  <div className={styles.btn}>
    <Button size="small" onClick={handlePrev}>Prev</Button>
    <Button size="small" onClick={handleNext}>Next</Button>
  </div>
  <div className={styles.page}>Page {pageNumber} </div>
</div>

</Container>

          <Container>
            <div className={styles.latest_vacancies}>
              <div className={styles.block_wrapper}>

                {paginatedPosts.map((item: any, i: number) => (
                  <div className={styles.block} key={i}>
                    <Card sx={{ minWidth: 275 }} className={styles.wide_card} onClick={runThis}>
                      <CardContent>
                        <h4>{item.title} </h4>
                        <div className={styles.inner_block}>
                          <p className={styles.org}>{item.organisationName} </p>
                          <p className={styles.closing_date}>{new Date(item.closingDate).toLocaleDateString('en-GB')} </p>
                          <p className={styles.location}>{item.location} </p>
                        </div>
                      </CardContent>
                    </Card>
                  </div>

                ))}
              </div>
            </div>
          </Container>

        </main>

        <footer className={styles.footer}>
          <Container>

            <div className={styles.pagination}>
              <div className={styles.btn}>
                <Button size="small" onClick={handlePrev}>Prev</Button>
                <Button size="small" onClick={handleNext}>Next</Button>
              </div>
              <div className={styles.page}>Page {pageNumber} </div>
            </div>

          </Container>

        </footer>
      </div>

    </>
  )
}

export default Home
